/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DownloadsDownloadIdRouteImport } from './routes/downloads.$downloadId'
import { Route as SettingsAccountsRouteImport } from './routes/settings.accounts'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsDownloadsRouteImport } from './routes/settings.downloads'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsProxiesRouteImport } from './routes/settings.proxies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsDownloadIdRoute = DownloadsDownloadIdRouteImport.update({
  id: '/$downloadId',
  path: '/$downloadId',
  getParentRoute: () => DownloadsRoute,
} as any)
const SettingsAccountsRoute = SettingsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDownloadsRoute = SettingsDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProxiesRoute = SettingsProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/downloads/$downloadId': typeof DownloadsDownloadIdRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/downloads': typeof SettingsDownloadsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/proxies': typeof SettingsProxiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/downloads/$downloadId': typeof DownloadsDownloadIdRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/downloads': typeof SettingsDownloadsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/proxies': typeof SettingsProxiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/downloads/$downloadId': typeof DownloadsDownloadIdRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/downloads': typeof SettingsDownloadsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/proxies': typeof SettingsProxiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/login'
    | '/settings'
    | '/setup'
    | '/downloads/$downloadId'
    | '/settings/accounts'
    | '/settings/appearance'
    | '/settings/downloads'
    | '/settings/general'
    | '/settings/proxies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/login'
    | '/settings'
    | '/setup'
    | '/downloads/$downloadId'
    | '/settings/accounts'
    | '/settings/appearance'
    | '/settings/downloads'
    | '/settings/general'
    | '/settings/proxies'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/login'
    | '/settings'
    | '/setup'
    | '/downloads/$downloadId'
    | '/settings/accounts'
    | '/settings/appearance'
    | '/settings/downloads'
    | '/settings/general'
    | '/settings/proxies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/$downloadId': {
      id: '/downloads/$downloadId'
      path: '/$downloadId'
      fullPath: '/downloads/$downloadId'
      preLoaderRoute: typeof DownloadsDownloadIdRouteImport
      parentRoute: typeof DownloadsRoute
    }
    '/settings/accounts': {
      id: '/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof SettingsAccountsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/downloads': {
      id: '/settings/downloads'
      path: '/downloads'
      fullPath: '/settings/downloads'
      preLoaderRoute: typeof SettingsDownloadsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/proxies': {
      id: '/settings/proxies'
      path: '/proxies'
      fullPath: '/settings/proxies'
      preLoaderRoute: typeof SettingsProxiesRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface DownloadsRouteChildren {
  DownloadsDownloadIdRoute: typeof DownloadsDownloadIdRoute
}

const DownloadsRouteChildren: DownloadsRouteChildren = {
  DownloadsDownloadIdRoute: DownloadsDownloadIdRoute,
}

const DownloadsRouteWithChildren = DownloadsRoute._addFileChildren(
  DownloadsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountsRoute: typeof SettingsAccountsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDownloadsRoute: typeof SettingsDownloadsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsProxiesRoute: typeof SettingsProxiesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountsRoute: SettingsAccountsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDownloadsRoute: SettingsDownloadsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsProxiesRoute: SettingsProxiesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
